dirs-y += src/indx 
src-y += indx/ir_sensor.c++ indx/heater.c++ indx/coil_driver.c++ indx/pid.c++ indx/i2c_bus.c++
src-y += indx/status_led_driver.c++ indx/external_clocks.c++
CFLAGS_klipper.elf += -lm
